### ISSUE TITLE
How can i run this demo?

### ISSUE THREAD

**Issue by Gakkifan1314** [FedericoSentineri00/BIRCH_Clustering#1]
Hi ,i have to use c/c++ to run birch-algorithm-clustering.Fortunately I find this,But I can't run this! can you tell me the details of this demo?
such as :I find this include a.h include b.h but b.h also include a.h.

**Comment by FedericoSentineri00** [comment]
Hello,
The project is a Master University that's is not complete and we are working on. 
I think it will take up to 1 month to be completed, so now is not working.
